# -*- coding: utf-8 -*-
"""Fake News Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laqF7Fmha2OfQRwc6IkUqlFUif1Lgxy5
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/news.csv")

df.head(3)

df.info()

df.isnull().sum()

df["content"] = df["title"] + " " + df["text"]

X = df["content"]

y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

df["content"] = df["content"].fillna("")

vectorizer = TfidfVectorizer(stop_words='english',
                             max_df=0.7)

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

model = LogisticRegression()

model.fit(X_train, y_train)

prediction = model.predict(X_test)

accuracy_score(y_test, prediction)

import pickle

pickle.dump(model, open("model.pkl","wb"))

pickle.dump(vectorizer,
            open("vectorizer.pkl","wb"))

